### ISSUE TITLE
"(0 , util_1.promisify) is not a function" in Cloudflare Worker

### ISSUE THREAD

**Issue by maxmandia** [axiomhq/axiom-node#105]
Hi all, 

Getting the above error in my cloudflare worker. Below is the specific line of code where the error is taking place in client.js:

` const encoded = yield (0, util_1.promisify)(zlib_1.gzip)(json);`

**Comment by bahlo** [comment]
Hi @maxmandia, sorry for getting back so late! This library is for the node environment and not compatible with Cloudflare Workers.

But I have good news: We're working on a cross-platform successor at [@axiomhq/js](https://github.com/axiomhq/axiom-js/tree/main/packages/js), give that a try and let us know if you run into any issues 🙌
