### ISSUE TITLE
New transport : pino-axiom

### ISSUE THREAD

**Issue by qlaffont** [axiomhq/axiom-node#131]
Hello,
I just submit this issue just to inform that I have created Axiom transport for Pino (https://github.com/pinojs/pino). ^^

More info : https://github.com/qlaffont/pino-axiom

Regards

Quentin

**Comment by bahlo** [comment]
Hi, that's really cool! We have a logger in https://github.com/axiomhq/axiom-js/tree/main/packages/pino—happy to take PRs that improves that one 🙏
