### ISSUE TITLE
aplQuery incorrectly requires `streamingDuration` and `noCache` when options are passed

### ISSUE THREAD

**Issue by RossWilliams** [axiomhq/axiom-node#74]
The type definition for `aplQuery`'s second parameter requires `streamingDuration` and `noCache` to be passed. However, these are not required and the query works fine if I bypass the type checks.

Consider marking these properties as optional.

**Comment by lukasmalkmus** [comment]
Thanks for the report. As you can imagine, holidays leave us a bit less responsive than usual.

If you fancy it, you can also create a PR for the team to look at.

Cheers and thanks again!

**Comment by lukasmalkmus** [comment]
Resolved by @schehata in #74.
