### ISSUE TITLE
AxiomClient is not a constructor

### ISSUE THREAD

**Issue by Amatewasu** [axiomhq/axiom-node#75]
Hi, first of all thank you for this library.

I struggle to initialize the client though.

Here's my TypeScript code that crashes:
```ts
import AxiomClient from '@axiomhq/axiom-node';

const AXIOM_ORG_ID = process.env.AXIOM_ORG_ID;
const AXIOM_TOKEN = process.env.AXIOM_TOKEN;

if (!AXIOM_ORG_ID || !AXIOM_TOKEN) {
  throw new Error('No AXIOM_ORG_ID or AXIOM_TOKEN');
}

const axiomClient = new AxiomClient({
  orgId: AXIOM_ORG_ID,
  token: AXIOM_TOKEN,
});
```

The output error is the following:
```
TypeError: AxiomClient is not a constructor
```

In theory it should works fine, right?

Node version used: v17.9.1
axiom-node version used: 0.10.0 (latest)
OS: Windows 11

Have a great day!

**Comment by Amatewasu** [comment]
Thanks for your answer. My editor nor TypeScript did not complain about it. It is super weird because if I go to the module's code, I clearly see that the constructor is defined... I can't think of a reason that might cause this either.

**Comment by schehata** [comment]
hmmm, maybe you override AxiomClient somewhere? if you can reproduce this in a repo I can help figure out the problem.

**Comment by kannthu** [comment]
I just had the same issue - the fix for it was to change `"moduleResolution": "nodenext",` to `"moduleResolution": "node",` in the `tsconfig.json` file.
