### ISSUE TITLE
Using Axiom with winston - is it asynchronous ?

### ISSUE THREAD

**Issue by jeanhdev** [axiomhq/axiom-node#91]
After reading a bit about `winston` logger, it looks like it's not asynchronous. In the `winston` example of the repos, there's no `await` in front of the logger call which is weird. In the vanilla `axiom-node` example, there is an await.

I'm asking because I'm testing AWS Lambdas and I see the first logs but never the last ones that should execute, which presumably, don't because they don't have time to complete as the Lambda returns and exits before. 

So my question is - if using`winston`, how does the asynchronous aspect works?

Many thanks

**Comment by ImLunaHey** [comment]
This is a winston issue, it doesn't guarantee messages are flushed on process exit.

https://stackoverflow.com/questions/18771707/how-to-flush-winston-logs
