### ISSUE TITLE
(Node) Client is not a constructor

### ISSUE THREAD

**Issue by hassantsyed** [axiomhq/axiom-node#93]
`const client = new Client();
await client.ingestEvents('dataset',[...]);`

const client = new Client();
               ^

TypeError: Client is not a constructor

How can I fix this?

**Comment by lukasmalkmus** [comment]
Is this possibly a duplicate of #75 and does [this comment](https://github.com/axiomhq/axiom-node/issues/75#issuecomment-1405042084) help?

**Comment by hassantsyed** [comment]
I did see that issue, unfortunately, it did not help.

**Comment by hassantsyed** [comment]
Resolved, Thanks!
